export const ASSETS_CDN_BASE =
  (import.meta.env.VITE_ASSETS_CDN_BASE as string | undefined) ?? "";

export const CONFIG = {
  seed: 424242,
  simDt: 1 / 60,
  camera: {
    fov: 64,
    near: 0.1,
    far: 16000,
    lookAheadDistance: 28,
    eyeHeight: 2.2,
    eyeBackOffset: 1.0,
    swayFrequency: 1.75,
    swayAmplitude: 0.05,
  },
  train: {
    mass: 20000,
    tractionForceMax: 80000,
    brakeForceMax: 135000,
    dragCoefficient: 30,
    rollingResistance: 1500,
    maxSpeed: 60,
    throttleRatePerSecond: 0.7,
    brakeRampSeconds: 0.8,
  },
  comfort: {
    max: 100,
    regenRate: 1.8,
    overspeedPenaltyRate: 1.8,
    hardBrakeThreshold: -2.4,
    hardBrakePenaltyRate: 4.5,
    jerkThreshold: 2.8,
    jerkPenaltyRate: 0.4,
  },
  audio: {
    movementTrackSrcs: Array.from(
      { length: 12 },
      (_, i) => `${ASSETS_CDN_BASE}/loops/tt${i + 1}.mp3`,
    ),
    movementThreshold: 0.0,
    minVolume: 0.0,
    maxVolume: 0.2,
    movementReleaseFadeSeconds: 0.5,
    brakeTrackSrcs: Array.from(
      { length: 4 },
      (_, i) => `${ASSETS_CDN_BASE}/loops/tb${i + 1}.mp3`,
    ),
    brakePressureThreshold: 0.02,
    brakeMinVolume: 0,
    brakeMaxVolume: 0.15,
    brakeReleaseFadeSeconds: 0.35,
    ambientTrackSrcs: [
      `${ASSETS_CDN_BASE}/ambient1.mp3`,
      `${ASSETS_CDN_BASE}/ambient2.mp3`,
      `${ASSETS_CDN_BASE}/ambient3.mp3`,
      `${ASSETS_CDN_BASE}/ambient4.mp3`,
    ],
    ambientVolume: 0.05,
    ambientMinGapMs: 10_000,
    ambientMaxGapMs: 20_000,
    musicTrackSrcs: [
      `${ASSETS_CDN_BASE}/track1.mp3`,
      `${ASSETS_CDN_BASE}/track2.mp3`,
      `${ASSETS_CDN_BASE}/track3.mp3`,
      `${ASSETS_CDN_BASE}/track4.mp3`,
    ],
    musicVolume: 0.3,
    musicFadeInMs: 4_000,
    // Tracks are 60 s long with a hard cut. Fade out starts at 50 s, giving
    // 10 s of headroom so the abrupt ending is never heard.
    musicFadeOutAtMs: 50_000,
    musicFadeOutMs: 8_000,
    musicGapMs: 4_000,
  },
  track: {
    segmentCount: 180,
    segmentLength: 12,
    stemLength: 40,
    maxHeadingDelta: 0.08,
    curvatureNoiseScale: 0.0018,
    detailNoiseScale: 0.008,
    baseCurvaturePerMeter: 0.0055,
    detailCurvaturePerMeter: 0.003,
    headingDamping: 0.0001,
    biasTracking: 0.004,
    lateralPull: 0,
    originWarpStrength: 0.42,
    railGauge: 1.25,
    sampleCountForMesh: 2800,
    railSegmentLength: 1.25,
    sleeperSpacing: 1.6,
    ballastWidth: 4.2,
    ballastHeight: 0.38,
    ballastTopOffset: -0.12,
    ballastSideTaper: 1.5,
    railWidth: 0.11,
    railHeight: 0.16,
    railBaseOffset: 0.18,
    sleeperWidth: 2.9,
    sleeperHeight: 0.14,
    sleeperDepth: 0.26,
    sleeperBaseOffset: 0.06,
    maxGenerationAttempts: 8,
  },
  terrain: {
    worldSize: 16000,
    gridResolution: 280,
    maxHeight: 95,
    noiseScale: 650,
    noiseOctaves: 5,
    noisePersistence: 0.53,
    noiseLacunarity: 2.08,
    trackSampleSpacing: 8,
    trackFlattenInner: 7,
    trackFlattenOuter: 28,
    trackBedInset: 0.32,
    trackBulgeHeight: 0.2,
    trackBulgeRadius: 4.5,
    trackShoulderOffset: 7.5,
    trackShoulderWidth: 3.4,
    trackShoulderDepth: 1.25,
    mountainBlendRadius: 640,
    radialRiseStart: 20,
    radialRiseRange: 300,
    radialRiseHeight: 210,
    radialRisePower: 1.2,
    radialRiseNoiseScale: 0.0018,
    radialRiseNoiseStrength: 0.22,
  },
  forest: {
    treeSpacing: 46,
    treeBandNear: 8,
    treeBandFar: 72,
    spawnChancePerSide: 0.36,
    lateralJitter: 8,
    forwardJitter: 14,
    minHeightScale: 0.78,
    maxHeightScale: 1.62,
    trackTreeClearDistance: 8,
    trackTreeFadeDistance: 26,
  },
  grass: {
    clumpSpacing: 4.5,
    bladesPerClump: 18,
    maxBladeCount: 70000,
    spawnChancePerSide: 0.92,
    bandNear: 5.5,
    bandFar: 62,
    lateralJitter: 8,
    forwardJitter: 2.8,
    clumpRadius: 2.1,
    trackClearDistance: 5.8,
    trackFadeDistance: 18,
    bladeBaseHeight: 1.05,
    bladeBaseWidth: 0.11,
    bladeHeightVariance: 0.55,
    bladeWidthVariance: 0.35,
    bladeRootOffset: 0.02,
    accentFrequency: 0.06,
    tintVariation: 0.18,
    slopeSampleStep: 1.45,
    slopeMin: 0.4,
    slopeMax: 1.55,
    densityNoiseScale: 0.028,
    densityThresholdMin: 0.28,
    windStrength: 0.32,
    windSpeed: 1.15,
    windSpatialFrequency: 0.96,
    fadeStart: 150,
    fadeEnd: 275,
    rootDarken: 0.5,
    tipLighten: 1.18,
    fieldColor: "#79a655",
    patchColor: "#95be63",
  },
  birds: {
    count: 160,
    bounds: 52,
    anchorDistance: 48,
    anchorHeight: 28,
    anchorSmoothing: 2.4,
    minSpeed: 1.2,
    maxSpeed: 3.8,
  },
  minimap: {
    previewDistances: [10, 25, 40, 60, 85, 115],
    pathLookAheadDistance: 170,
    pathSampleSpacing: 5,
    safeSpeedBase: 6.8,
    safeSpeedMin: 8,
    safeSpeedMax: 36,
    curvatureEpsilon: 0.0006,
  },
  terminal: {
    bumperOffsetFromTrackEnd: 3.4,
    stationLength: 122,
    stationGapToBumper: 12,
    stopSpeedThreshold: 0.35,
    signDistancesFromBumper: [300, 220, 150, 90, 50],
    signLateralOffset: 6.8,
    platformWidth: 7.6,
    platformHeight: 0.32,
    platformLateralOffset: 5.1,
    platformSegmentLength: 10,
  },
} as const;
